config/routes.rb
Rails.application.routes.draw do
  resources :tasks
  root 'tasks#index'
end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :tasks
end

app/models/task.rb
class Task < ActiveRecord::Base
  belongs_to :category
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :find_task, only: [:show, :edit, :update, :destroy]

  def index
    if params[:category].blank?
      @tasks = Task.all.order("created_at DESC")
    else
      @category_id = Category.find_by(name: params[:category]).id
      @tasks = Task.where(category_id: @category_id).order("created_at DESC")
    end
  end

  def show
  end

  def new
    @task = Task.new
  end

  def create
    @task = Task.new(tasks_params)

    if @task.save
      redirect_to @task
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @task.update(tasks_params)
      redirect_to @task
    else
      render :edit
    end
  end

  def destroy
    @task.destroy
    redirect_to root_path
  end

  private

  def tasks_params
    params.require(:task).permit(:title, :description, :company, :url, :category_id)
  end

  def find_task
    @task = Task.find(params[:id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Rabbit</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <nav class="navbar navbar-default">
    <div class="container">
      <div class="navbar-brand">
        TaskRabbit
      </div>
      <ul class="nav navbar-nav">
        <li>
          <%= link_to 'All tasks', root_path %>

          <% Category.all.each do |category| %>
            <li>
              <%= link_to category.name, tasks_path(category: category.name) %>
            </li>
          <% end %>
        </li>
        <%= link_to 'New task', new_task_path, class: 'navbar-text navbar-right navbar-link' %>
      </ul>
    </div>
  </nav>
  
  <div class="container">
    <div class="col-md-8 col-md-offset-2">
      <%= yield %>
    </div>
  </div>
</body>
</html>

app/views/tasks/_form.html.erb
<div class="row">
  <div class="col-md-12">
    
    <%= form_for(@task, html: {class: "form-horizontal", role: "form"}) do |f| %>

      <div class="form-group">
        <div class="control-label col-md-3">
          <%= f.label :task_title %>  
        </div>
        <div class="col-md-9">
          <%= f.text_field :title, class: 'form-control', autofocus: true %>  
        </div>
      </div>

      <div class="form-group">
        <div class="control-label col-md-3">
          <%= f.label :category %>  
        </div>
        <div class="col-md-9">
          <%= f.collection_select :category_id, Category.all, :id, :name, {prompt: "Select a category"}, {class: "btn btn-sm dropdown-toggle"} %>
         </div>
      </div>

      <div class="form-group">
        <div class="control-label col-md-3">
          <%= f.label :task_description %>
        </div>
        <div class="col-md-9">
          <%= f.text_area :description, class: 'form-control' %>  
        </div>
      </div>

      <div class="form-group">
        <div class="control-label col-md-3">
          <%= f.label :your_company %>
        </div>
        <div class="col-md-9">
          <%= f.text_field :company, class: 'form-control' %>  
        </div>
      </div>

      <div class="form-group">
        <div class="control-label col-md-3">
          <%= f.label :link_to_task %>
        </div>
        <div class="col-md-9">
          <%= f.text_field :url, class: 'form-control' %>  
        </div>
      </div>
      
      <br />  

      
  
      <div class="form-group">
        <div class="col-md-offset-3 col-md-9">
          <%= f.submit class: 'btn btn-default' %> 
          <%= link_to 'Back', root_path,class: 'btn btn-link' %>
        </div>
        
      </div>
      
    <% end %>

    
  </div>
</div>

app/views/tasks/edit.html.erb
<%= render 'form' %>

app/views/tasks/index.html.erb
<div id='jobs'>
  <% @tasks.each do |task| %>
    <div class="job">
      <h2><%= link_to task.title, task %></h2>
      <p><%= task.company %></p>
    </div>
  <% end %>
</div>

app/views/tasks/new.html.erb
<%= render 'form' %>

app/views/tasks/show.html.erb
<div id="jobs">
  <div class="job">
    <h1><%= @task.title %></h1>
    <p><%= @task.description %></p>
    <p><%= @task.company %></p>
    <p><%= @task.category.name %></p>
    <button class="btn btn-default"> 
      <%= link_to 'Complete task', @task.url, target: '_blank' %>
    </button>
  </div>

  <div id="links">
    <%= link_to 'Home', root_path, class: 'btn btn-sm btn-default' %>
    <%= link_to 'Edit', edit_task_path(@task), class: 'btn btn-sm btn-default' %>
    <%= link_to 'Delete', task_path(@task), method: :delete, data: {confirm: 'Are you sure?'} , class: 'btn btn-sm btn-danger' %>
  </div>
</div>